In [1]:
import gym

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.


In [2]:
env = gym.make('CartPole-v0')

C:\Users\DELL\anaconda3\Lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


In [5]:
env.reset()

(array([ 0.0044744 , -0.03686006,  0.04182643, -0.01089216], dtype=float32),
 {})

In [6]:
for _ in range(1000):
     env.render()
     env.step(env.action_space.sample())

C:\Users\DELL\anaconda3\Lib\site-packages\gym\envs\classic_control\cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v0", render_mode="rgb_array")
  gym.logger.warn(
C:\Users\DELL\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
C:\Users\DELL\anaconda3\Lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


In [9]:
import gym
env = gym.make('CartPole-v0')

C:\Users\DELL\anaconda3\Lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(


In [11]:
for i_episode in range(20):
    observation = env.reset()

In [37]:
for t in range(100):
        env.render()  # Renders our cartpole environment
        print(observation)
        
        action = env.action_space.sample()  # Takes random action from action space
    
        observation , reward, info, done,hello = env.step(action)
        
        if done:
            # Prints number of timesteps it took to finish the episode
            print("Episode finished after {} timesteps".format(t+1))
            break

(array([-0.00094774, -0.03534067, -0.00816281, -0.01767258], dtype=float32), {})
[ 0.45166945  0.858857   -4.7389135   4.464765  ]
[ 0.4688466  0.6947922 -4.649618   4.7651887]
[ 0.48274243  0.89810365 -4.5543146   5.07774   ]
[ 0.50070447  0.74124515 -4.4527597   5.331036  ]
[ 0.5155294   0.95229787 -4.346139    5.696456  ]
[ 0.53457534  1.1680138  -4.23221     6.086834  ]
[ 0.55793566  1.3883857  -4.110473    6.5002832 ]
[ 0.5857034  1.2412497 -3.9804676  6.617646 ]
[ 0.61052835  1.0911193  -3.8481147   6.685852  ]
[ 0.63235074  0.93616885 -3.7143977   6.699926  ]
[ 0.6510741  1.1568165 -3.580399   7.1374145]
[ 0.6742104  1.3756791 -3.437651   7.5595145]
[ 0.701724   1.5897359 -3.2864606  7.9524055]
[ 0.7335187  1.4058499 -3.1274126  7.721908 ]
[ 0.7616357  1.5999408 -2.9729743  8.008846 ]
[ 0.79363453  1.3923723  -2.8127973   7.65257   ]
[ 0.821482  1.176069 -2.659746  7.250562]
[ 0.84500337  1.3389739  -2.5147347   7.3308525 ]
[ 0.87178284  1.4926572  -2.3681176   7.3450875 ]
[ 0.9